package edu.mit.ll.vizlincdb.graph;

/**
 * Superclass for exceptions generated by VizLincDB classes.
 */
public class VizLincDBException extends Exception {

    public VizLincDBException(String msg) {
        super(msg);
    }
    
}
